### PR TITLE
In string this.line should be boolean.

### PR DESCRIPTION
**Pull request by martinfrances107**
Within string.js I want to change the type of this.line to boolean 

it is only ever set to one of two values. '0' or NAN

and only every read in a if statement.

Also but not included.I would suggest changing the name as it does not immediately describe what is its purpose.

### CODE REVIEW

**Comment by Fil** [comment]
(I know your question is not about what happens, I'm just trying to spell it out for myself.)

This variable is a state in a finite-state automaton. The current notation has the benefit of being the same for _line (binary), and _point (ternary):

`_line`:
- 0 = in a polygon (lines should be closed)
- NaN = not in a polygon (lines should not be closed)

`_point`:
- NaN = not in a line (each point creates a [circle at x,y])
- 0 = in a line, a point at the beginning [M x,y]
- 1 = in a line, a point in the continuity [L x,y].

The names could be clearer.

**Comment by martinfrances107** [comment]
Thanks for taking a look at this ...

When I rewrote this code in rust ... where enums are really useful .. I went with three possible states.
for _point.

#[derive(Clone, Debug)]
enum PointState {
    LineAtStart,
    LineInProgress,
    LineNotInProgress,
}

I don't want to appear a grizzled old misanthrope .. constantly submitting tiny patch no one else cares about...

So it really depends on your time ... If I submitted a patch with a better name for _line 
and maybe give _line and _point enums ... (well as good as you can emulate get in javascript)

Would that be something you care about reviewing?

I think the RUST version with enums has much better flow when I glance at it.

**Comment by Fil** [comment]
Your reviews, patches and comments are much appreciated—the more we can proofread, strengthen, and document this code the better.

**Comment by martinfrances107** [comment]
Ok so I added a enum like structure for the variable point.

I was trying to change to minimum amount of code.

I don't think _line and _point are good names .. but I think now  point transitions between labelled  states improves readability.

From a code review point of view .. the initial value of point is initially undefined and then takes on the correct values assuming the code flows in the way the designer intended... a more paranoid/defensive approach would be to demand an initial value.

I am happy to make any changes to this.

**Comment by Fil** [comment]
I don't know… I appreciate the discussion and clarification, but I'm not convinced we have to change the code. (What I'd really want for d3-geo is to exist as a collection of explanatory notebooks that would document each of the sometimes very subtle algorithms it contains.)

**Comment by martinfrances107** [comment]
Ok, fair enough, thanks for hearing me out.

**Pull request closed without merging**
