### PR TITLE
Fix polygonContains(polygon, pole) when the polygon goes through a pole.

### LINKED ISSUE #105: Geometries that touch the south pole may be rendered incorrectly.
Hello,
I have found that a converse including area happens when a polygon touches the south pole in equirectangular projection on a special condition as follows:

equirectangular1

equirectangular2

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
  .poly {
  fill: #fa0;
  fill-opacity: .2;
  stroke: #f00;
  stroke-width: .5px;
  }
  .graticule {
  fill: none;
  stroke: #777;
  stroke-width: 0.3px;
  stroke-opacity: 0.5;
  }
  </style>
  <title></title>
</head>
<body>
  <script src="https://d3js.org/d3.v4.min.js"></script> 
  <script>

  var poly = [[0, -30], [120, -30], [0, -90], [0, -30]];
  var width = 600, height = 320, centerProjection = [-80, 0];
  var scaleProj = Math.min(width/2, height)/Math.PI;
  var projection = d3.geoEquirectangular()
  .translate([width/2, height/2]).scale(scaleProj)
  .rotate([-centerProjection[0], -centerProjection[1]]);
  var path = d3.geoPath().projection(projection);
  var graticule = d3.geoGraticule();

  var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
    .call(d3.drag()
      .subject(function() {var rotate = projection.rotate(); return {x: 2*rotate[0], y: -2*rotate[1]};})
      .on("drag", function() {
        projection.rotate([d3.event.x/2, -d3.event.y/2, projection.rotate()[2]]);
        svg.selectAll("path").attr("d", path);
      }));
      
  svg.append("path")
    .datum({type: "Polygon", coordinates: [poly]})
    .attr("class", "poly")
    .attr("d", path);

  svg.selectAll(".graticule")
    .data(graticule.lines)
    .enter().append("path")
    .attr("class", "graticule")
    .attr("d", path);

  </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #105. Supersedes #127.

(@Fil for future, if you develop your PRs as branches in this repo rather than in your own fork of d3-geo then it’ll be easier for us to collaborate on the same branch before merging to master.)

### CODE REVIEW

**Comment by Fil** [comment]
OK will do that for the next PR — it's just that, after I accidentally pushed some cruft to `master`, I chose to be more conservative for a while :)

I'm not too sure about the simplification: the issue arises in that zone around ±1 where asin() can't discriminate enough (numerically) between, say, 90 and 89.9999999 degrees (see https://beta.observablehq.com/@fil/asin-danger-zone). After a few rotations there is inevitably some drift, and testing phi === ± halfPi might fail to protect us from #105 .

**Comment by mbostock** [comment]
Is it worth doing a check like this, then?

```js
if (phi > halfPi - epsilon) phi = halfPi + epsilon;
else if (phi < epsilon - halfPi) phi = -halfPi - epsilon;
```

**Comment by Fil** [comment]
I don't know. My notebook shows that the limit is around 1e-6 / 1e-7 on my
computer & browser, so it might or not be comparable with epsilon = 1e-6 on
another computer.

But what's wrong with this sin()? I'd understand caution if it ran for each
point of the polygon, but unless I'm mistaken it's at most once per polygon
ring.

**Comment by mbostock** [comment]
Okay, switched to the more conservative test.

**Pull request merged**
