### PR TITLE
Attempt to add mercator #30

### PR DESCRIPTION
**Pull request by curran**
Copied source from https://github.com/d3/d3/blob/9cc9a875e636a1dcf36cc1e07bdf77e1ad6e2c74/src/geo/mercator.js , based on the structure of some of the projections there. I'm kind of doing this blindly, but I want to contribute. Please let me know what the shortcomings are here. Thank you.

### CODE REVIEW

**Comment by mbostock** [comment]
This isn’t quite enough because the Mercator projection also needs to implement the default clipExtent… I’ll work on it.

**Comment by mbostock** [comment]
Okay, done!

**Comment by curran** [comment]
Awesome! I will try to learn more about the default clipExtent, I don't quite understand it.

**Comment by mbostock** [comment]
The relevant line from [Wikipedia on Mercator](https://en.wikipedia.org/wiki/Mercator_projection#Truncation_and_aspect_ratio):

> The ordinate y of the Mercator projection becomes infinite at the poles and the map must be truncated at some latitude less than ninety degrees. This need not be done symmetrically. Mercator's original map is truncated at 80°N and 66°S with the result that European countries were moved towards the centre of the map. The aspect ratio of his map is 198 / 120 = 1.65. Even more extreme truncations have been used: a Finnish school atlas was truncated at approximately 76°N and 56°S, an aspect ratio of 1.97. Much web based mapping uses a zoomable version of the Mercator projection with an aspect ratio of unity. In this case the maximum latitude attained must correspond to y = ±W / 2, or equivalently y / R = π.

**Comment by curran** [comment]
Thank you for the reference. Very interesting!

**Pull request merged**
