### PR TITLE
Add projection.reflectX / reflectY to all projections.

### PR DESCRIPTION
**Pull request by Fil**
Capture d’écran 2020-01-02 à 22 55 29

### CODE REVIEW

**Comment by Fil** [comment]
Complete demo: https://observablehq.com/d/cc7d6a3599a5555b

**Comment by mbostock** [comment]
Interesting. What’s the use case? And is there any appreciable performance cost?

**Comment by Fil** [comment]
It came from a discussion with @nbremer about how to display astronomical data. The orb is seen from below: right ascension (eastern direction) should point to the left when North is pointing up.

The solution currently is to use a raw projection and manually negate *x*, as we do for the "back projection" of https://observablehq.com/@fil/translucent-earth (which would be another use case).

The only change in computing a projected point or an inverse is we do `x *= sx; y *= sy;` for each point, with `sx=sy=1` in the general case.

(reflectY has no use case (that I'm aware of) for general maps, but I figured it would be simpler to have parity between geoIdentity and projections.)

**Comment by nbremer** [comment]
Indeed, astronomical maps are almost always reflected in the `x`, see [this map](http://www.skymaps.com/store/posters/NG-The-Heavens-large.jpg) for a Stereographic version, or [this one of the Milky Way](http://www.esa.int/ESA_Multimedia/Images/2018/04/Gaia_s_sky_in_colour2) in Aitoff projection.

**Pull request merged**
