### PR TITLE
Make .angle() a first class method of projectionMutator?

### PR DESCRIPTION
**Pull request by Fil**
Polyhedral projections allow to set the angle at the origin (i.e. the root face), making it possible to rotate the whole drawing. I'd like to make this a first-class method for all projections.

As discussed in [this comment](https://github.com/d3/d3-geo-projection/issues/118#issuecomment-306812547) we want to be careful of the cost, and context transform (in SVG or canvas) is probably cheaper.

However, the angle' sine and cosine can be computed when setting up the rotation, so the cost is just 1 2D-matrix multiplication per point. And even this cost can be avoided in the general case with a simple test on _s == 0_.

The main argument is that, unlike context transform, an .angle() method works well with .fitExtent().

Example:
```
d3.geoEquirectangular().clipAngle(90)
  .angle(30)
  .precision(0.1)
  .fitExtent([[0,0],[width,height]], {type:"Sphere"});
```
angleorient30

I have also checked that this builds correctly with d3-geo-projection: `gilbert` needs a 1 line patch.

### CODE REVIEW

**Comment by mbostock** [comment]
The README should make clearer that this rotation happens *after* projecting (*i.e.*, it’s a planar rotation) rather than *before*, as *projection*.rotate does.

Regarding the implementation, my first thought was using `compose` (or similar) to encapsulate this transformation in the existing `projectRotate` function? This should be faster since it avoids the `if (t.s)` in the inner loop when this feature will not be needed by the majority of projections.

But perhaps it would be cleaner if you generalized the projection to have a 2D transformation matrix after applying the spherical-to-planar projection. So given a matrix:

```
a b
c d
```

Then you’d say:

```js
function projection(point) {
  point = projectRotate(point[0] * radians, point[1] * radians);
  var x = point[0], y = point[1];
  return [x * a + y * c, x * b + y * d];
}
```

That should be general enough to incorporate all of our desired transforms (scale, translate, and “postrotate”) in a single arithmetic operation. So, *projection*.scale, *projection*.translate, *projection*.postrotate *etc.* would simply affect the internal values of *a* *b* *c* *d*.

Presumably, you need to also do the inverse transformation in *projection*.invert?

**Comment by mbostock** [comment]
Also seems like this change would mean we wouldn’t need a separate class for the transverse Mercator projection anymore, although we’d still need to provide a d3.geoTransverseMercatorRaw for backwards-compatibility.

**Comment by Fil** [comment]
for the transverse Mercator we can use
```
  mercatorProjection(mercatorRaw)
      .angle(90)
      .rotate([0,0,90])
      .scale(159.155);
```

but several tests fail, apparently because the sphere or clipExtent are not correct.

It's not far from working though:
transversemercator-difference

Another issue would be the way the default rotate() is set (`d3.geoTransverseMercator().rotate() === [0,0,0]`). I'm not sure it's worth sweating on this.

**Comment by Fil** [comment]
And here's a demo with this branch's build as of now
https://beta.observablehq.com/@fil/projection-angle

**Comment by Fil** [comment]
Ah, there is an issue with projection(projection.center()) not being equal to projection.translate() in some cases (polyhedral).

**Comment by mbostock** [comment]
I’ve created an [angle branch](https://github.com/d3/d3-geo/tree/angle) in this repo so that we can collaborate on this. I’m going to create a PR from that branch that will supersede this PR. I might also explore some tweaks in a separate branch for your review.

**Pull request closed without merging**
