### PR TITLE
#257 Remove duplicate test.

### PR DESCRIPTION
**Pull request by martinfrances107**
This test is repeated .. after removal the test can still be found at  line 19.

### CODE REVIEW

**Review by Fil — CHANGES_REQUESTED** [review]
good catch! please remove the changes introduced by prettier?

**Comment by martinfrances107** [comment]
Thanks for the prompt reply .... I have just force pushed the corrected version

**Review by Fil — APPROVED** [review]

**Comment by martinfrances107** [comment]
Can I ask what is the status of this...

Is there anything I need to do for this to be merged?

**Comment by Fil** [comment]
status was: forgot about it. Sorry!

**Pull request merged**
